### ISSUE TITLE
Complete the Phase 1 Review slides

### ISSUE THREAD

**Issue by rxlnj** [RSTV-24/Generating-Clear-Speech#4]
- [x] Problem Statement @vandanaa-s 
- [x] Scope @vandanaa-s 
- [x] Feasibility study @True-Fox 
- [x] Challenges @True-Fox 
- [x] Applications/Use cases @TanmayUdupa 
- [x] Expected Deliverables @rxlnj 
- [x] Capstone (Phase-I & Phase-II) Project Timeline @rxlnj 
- [ ] Preliminary Literature Review Summary @TanmayUdupa

**Comment by True-Fox** [comment]
Link: [Phase-1 Review Slides](https://docs.google.com/presentation/d/1pEwGynwGD85UMuugVcMTT_JMxAsjRUlqnO251by1rjk/edit#slide=id.p1)
